# Generated by Django 6.0.6 on 2026-07-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('carrera', models.CharField(max_length=120)),
                ('semestre', models.PositiveSmallIntegerField()),
                ('grupo', models.CharField(max_length=20)),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Mixto', 'Mixto')], max_length=20)),
                ('estatus_academico', models.CharField(choices=[('Activo', 'Activo'), ('Baja temporal', 'Baja temporal'), ('Baja definitiva', 'Baja definitiva'), ('Egresado', 'Egresado')], default='Activo', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(max_length=120)),
                ('area_academica', models.CharField(max_length=120)),
                ('estatus_laboral', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Permiso temporal', 'Permiso temporal')], default='Activo', max_length=30)),
                ('puede_capturar_calificaciones', models.BooleanField(default=True)),
                ('puede_registrar_asistencias', models.BooleanField(default=True)),
                ('puede_generar_reportes', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('carrera', models.CharField(max_length=120)),
                ('semestre', models.PositiveSmallIntegerField()),
                ('cupo_maximo', models.PositiveSmallIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('maestro_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='alumnos_maestros.maestro')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['carrera', 'semestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_escolar', models.CharField(max_length=30)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='alumnos_maestros.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='alumnos_maestros.materia')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('alumno', 'materia', 'periodo_escolar'), name='inscripcion_activa_unica')],
            },
        ),
    ]
